openapi: "3.1.1"
info:
  title: cat-playground
  version: "0.1.1"
paths:
  /echo:
    get:
      tags:
        - Dev
      operationId: echo
      summary: Echo the message
      description: Basic echo endpoint for testing
      parameters:
        - name: message
          in: query
          required: true
          schema:
            type: string
            default: "Hello, World!"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Echo"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Echo:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: The message to echo back
          example: "Hello World!"
    Error:
      type: object
      required:
        - message
      properties:
        title:
          type: string
          description: The error message
          example: "Unknown error"
        details:
          type: string
          description: The error details
          example: "Something bad happened"
