openapi: "3.1.1"
info:
  title: Kotki API
  version: "1.0"
servers:
  - url: https://api.kotki.com/v1
paths:
  /ping:
    get:
      parameters:
        - name: message
          in: query
          required: false
          schema:
            type: string
            default: "Pong"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ping"
components:
  schemas:
    ping:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: The message to return
          example: "Pong"
